### ISSUE TITLE
The "deploy preview" workflow needs to be updated as the output path has been changed

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hydephp.com#13]
A while ago we (_and by that I mean I_) changed the static site output directory for this repository from `_site` to `docs`. This inadvertently broke the preview workflow. It needs to be updated so the docs directory is pushed instead of _site. This is the workflow: [`deploy-preview.yml`](https://github.com/hydephp/hydephp.com/blob/master/.github/workflows/deploy-preview.yml). I think this is a great new first issue for Hacktoberfest! Let me know if you want to take this on, and if you need any help!

**Comment by lejara** [comment]
Heyo!

May i take this on?

**Comment by caendesilva** [comment]
Go for it! Let me know if you need any help!
