### ISSUE TITLE
Default navigation priority?

### ISSUE THREAD

**Issue by ameenross** [hydephp/hydephp.com#43]
I think I figured out that the default priority is `999`. I don't want to have to add priority to every page, I only really need the index page first and the contact page last. So I didn't want to add priority to every page. However I couldn't get the contact page to be the last item in the menu. Ironically I tried with `priority: 999`. So it works when I make it `1000` :)

However I couldn't find this default value in the docs. Would be nice to add it there.

**Comment by caendesilva** [comment]
Hey Ameen! Thanks for using HydePHP! You have great timing as I actually updated the documentation in the config regarding this a few days ago, and I am still working on a new draft for a clearer and more elaborate documentation on this. You can thus look forward to this in the next release of HydePHP!

You are correct that the default priority for pages is `999`. You can set a higher priority in the `hyde.navigation.order` config or in front matter using `navigation.priority`. You can use any value much higher than `999` if you need to.

I hope this clears things up, and don't hesitate to let me know if you need any other help!
